server:
  port: 9999
spring:
  profiles: dev
  datasource:
    driver-class-name:
      com.mysql.jdbc.Driver
    url:
      jdbc:mysql://localhost:3306/shiro_demo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username:
      root
    password:
      12345
