server:
  port: 9999
shiro:
  root: secret, admin
  guest: guest, guest
  presidentskroob: 12345, president
  darkhelmet: ludicrousspeed, darklord, schwartz
  aihe: aihe, goodguy, client

  # -----------------------------------------------------------------------------
  # Roles with assigned permissions
  # roleName : perm1, perm2, ..., permN
  # -----------------------------------------------------------------------------
roles:
  admin: *
  client: look:*
  goodguy: winnebago:drive:eagle5
spring:
  datasource:
    url:jdbc:mysql://localhost:3306/shiro_demo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username:root
    password:12345
    driver-class-name:com.mysql.jdbc.Driver
